on: [push]
jobs:
  circleci_artifacts_redirector_job:
    runs-on: ubuntu-latest
    if: "${{ github.event.context == 'ci/circleci: preview' }}"
    name: Collect CircleCI artifact links
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 16
          cache: yarn
      - uses: ./.github/actions/collect-circleci-artifact-links
